name: healthy_me
description: Healthy Me - simple, personalized health and fitness guidance.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.3
  file_picker: ^13.1.0
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
